name: Bug Report
description: Report a bug or issue with the template
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the problem you encountered...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run setup.sh
        2. Execute check-doc-pairs.sh
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Script should pass validation...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Script failed with error...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the template is affected?
      options:
        - Documentation
        - Scripts (setup, validation, etc.)
        - CI/CD Workflows
        - Agent Configuration
        - Diagrams
        - Templates
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 14]
        - Shell: [e.g., bash 5.1, zsh 5.9]
        - Git version: [e.g., 2.40.0]
        - Node version (if applicable): [e.g., 20.10.0]
      value: |
        - OS:
        - Shell:
        - Git version:
        - Node version:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Relevant error messages or logs
      placeholder: Paste error output here...
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: This started happening after...

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all requested information
          required: true
        - label: I have included error logs/output if applicable
          required: true
